-keep class org.xmlpull.** { *; }
-keepnames class * implements org.xmlpull.v1.XmlPullParser
-keepnames class * implements org.xmlpull.v1.XmlPullParserFactory
-keep class org.xmlpull.v1.XmlPullParserFactory
-keep class io.flutter.plugin.common.MethodChannel { *; }
-keepclassmembers class io.flutter.plugin.common.MethodChannel$* { *; }
-keep class kotlin.Metadata { *; }
-keep class com.example.my_android_plugin.** { *; }
-keep class com.apk.axml.** { *; }